version: "3.7"

services:
  spotify-api:
    build: ./back
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      - network
  spotify-client:
    build: ./front
    ports:
      - 3000:3000
    networks:
      - network
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: spotify
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - network

networks:
  network:
    external: true
    name: ${DOCKER_NETWORK}
